x<-c(2,3,5,7)
y<-c(14,13,36,10)
plot(x,y,type="o",col="blue",main="Scatter plot",pch=16,xlab="x-axis",ylab="Y-axis")
plot(x,y,type="p",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")
plot(x,y,type="l",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")
plot(x,y,type="b",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")
plot(x,y,type="h",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")
plot(x,y,type="s",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")
plot(x,y,type="n",col="blue",main="Scatter plot",xlab="x-axis",ylab="Y-axis")